import pandas as pd
from utils import rename_dataset_columns
from SentimentAnalyzer import SentimentAnalyzer


imdb_dataset = pd.read_csv("hf://datasets/scikit-learn/imdb/IMDB Dataset.csv")
imdb_dataset = imdb_dataset.rename(columns={'review':'text'})
print(imdb_dataset.head())

analyzer = SentimentAnalyzer(imdb_dataset)
print(analyzer.isPositive("""
                          Chester Bennington was 41 years old when he lost the battle he spent life urging people to overcome. The defining characteristic of Linkin Park’s music was how accessible it made the tools to deal with trauma, an offering intended both for their fans and Bennington himself. His death in 2017 was by all accounts a shock: to the band, to his family, and to the legions across the world who treated him as an inspiration, not just for his power as a singer, but for his dignity in recovery and honesty in relapses. He worked through years of sexual abuse and drug addiction on stage, on record, and through community outreach. For those who witnessed Bennington buoyant and free on stage just weeks before he died, the burden of presence is hard to shake. All of this weighs heavily on 2000’s Hybrid Theory, already the most popular heavy music of the 21st century. With global sales of 32 million—including 12 million in the U.S., a million of which has come in the past three years—Hybrid Theory is the highest-selling debut in any genre since 1988’s Appetite for Destruction. You’d assume being the only diamond-tinted rock album this side of the millennium might afford a smidgen of clout. Yet on lists of the best metal, hard rock, emo or straight-up rock, Hybrid Theory is often conspicuously absent, as if no axe-worshipping subtribe is willing to adopt it as their own.
Nu-metal would seem the obvious category, but even though Linkin Park were saddled with the tag at the time, it was an awkward fit. They knew the nu- was loaded: Their blend of rapping, screaming, and circuit-bending rendered them suspect to the double-denim dinosaurs of rock crit, so they built a street team on chatrooms and trained in on untapped admissions of despondency and failure. They sang about being filled with tension, feeling betrayed by the light, wishing for a way to disappear. In making themselves small, they became colossal.

Rather than re-re-evaluate the era in which they found fame, the 20th anniversary reissue of Hybrid Theory—featuring over 50 unreleased tracks, B-sides, remixes, live performances and rarities—encourages a closer examination of why this band went supernova. Today, it’s hard to look past the buddy act of Bennington and Mike Shinoda as the skeleton key that unlocked Linkin Park’s appeal for a wider spectrum of listeners. It almost didn’t happen. The group had been active for three years before the departure in 1999 of original singer Mark Wakefield (who went on to both manage Taproot and design the cover for System of a Down’s Toxicity). Even after Bennington was installed, Hybrid Theory’s demos show just how far they had to travel before arriving at anything resembling synergy. On early versions of “A Place for My Head” and “Points of Authority,” it seems as if Bennington and Shinoda are reading from different sheets entirely."""))